### ISSUE TITLE
Travis is using python 3.4 instead of 3.6

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-press#109]
It's possible to run into a difference between with what `make lint` does on the developer's system versus Travis.

I've come across one minor SyntaxError that passes in 3.6, but not in 3.4.

The ideal solution would be to upgrade to python3.6, but 3.6 isn't just available for use. We'd need to pull in ppa:deadsnakes or something else.

**Comment by pumazi** [comment]
It appears 3.6 is now supported by Travis. We should switch to that version as it is what we use in production. https://docs.travis-ci.com/user/languages/python/#specifying-python-versions

**Comment by Bkblodget** [comment]
Discussion from 3/5/19:

https://openstax.slack.com/archives/C0LA54Q5C/p1554479964232300

*summary:* this is still a problem and needs to be addressed.
