### ISSUE TITLE
Generalize project dependencies

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-press#156]
It's important to note direct dependencies without pinning them. However, it's also important to have a workflow that tests known good sets of dependencies.

For the time being #152 was put in place to ensure that any dependency upgrades run the tests within this project.

As M. Mulich, I want our dependency list separate from our pinned dependency list, so that we can tell which dependents are direct vs sub-dependencies and manage upgrades with package tooling.

---

I propose we use `pip-compile` to compile `requirement.in` (unpinned and direct dependent) files to `requirement.txt` (pinned with all sub-dependents). See [pip-tools](https://github.com/jazzband/pip-tools) for documentation about the usage of `pip-compile`.

**Comment by reedstrm** [comment]
I agree that this makes sense. Poking through the pip-tools blog posts eventually leads to pipenv https://docs.pipenv.org/ - do we want to consider going whole-hog? (seems it uses pip-tools internally)

**Comment by pumazi** [comment]
The pipenv tool looks cool. I don't know that it fits our scenario though. We aren't using virtualenv, except locally to install linting tools. I kinda like the simplicity of using pip-tools for this without bringing in a whole environment manager. Also, I know pyup will work with the results of pip-compile.

Interestingly, @m1yag1 has also informed me that the proposal is exactly what the hypothesis project does. 🎉

**Comment by brittweinstein** [comment]
This is largely addressed as part of #292. Closing.
