### ISSUE TITLE
Press should detect a major revision (within collxml). [Priority 2]

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-press#162]
# Description
Press needs to detect when a major version rev is needed for the collection, when a minor version rev is needed, and otherwise detect as unchanged. 

This is priority 2 for the Only Publish Changed Content epic. 

# PRs
#329, #333 and #334. All three based off of #190 .

# Test Plan
Major version rev should ONLY happen with the criteria listed. Changing other things like print style, summary, or keywords should give an error message which says that there have been no changes.

## Steps:
**First test**
1. **Using Neb**, make a change or a set of changes which should cause a major version rev (criteria listed below).
2. Publish the collection.
3. Neb get the latest collection after your changes have been published.
4. Verify that the new version is equal to previous version plus one, and the minor version is equal to one. This information is located in `collection.xml` -> `metadata` -> `md:version`.

**Second test**
Same steps as above but expect only the minor version to increase by 1 and the major version to remain the same

**Third test**
1. Again, using Neb, make a change or a set of changes which are not supposed to cause neither a major version rev nor a minor version rev.
2. Publish the collection.
3. Expect Neb to give an error message which says that there have been no changes.

# Criteria for causing major version rev
Any of the following should cause a major version revision:
1. Collection title changes (this does not include module title changes)
2. Collection contents structure changes – reordering, adding, or removing a module from `collection.xml`.

# Criteria for causing minor version rev
Any of the following should cause a minor version revision:
1. Abstract changes
1. Subject changes
2. Parameter changes
3. Collection or module actor changes
4. Collection or module role changes
5. Module version changes

---------------------------
# Description for the SAX-based Collection XML parser

Given a collxml document, parse the document to a python object/dictionary where collections and sub-collections (both branching points) contain subcollections and modules (leaf nodes).

### Technical details

The function should take a file-like object and convert/parse it to a structured hierarchical based on the information in the xml.

You can find examples of tree usage in the press tests. It's not necessary you use the same structural classes, but maybe that will be helpful.

Some example code that we have that does similar things:

- In press tests:
  - [the random generation of a tree](https://github.com/Connexions/cnx-press/blob/15a074fe27ffeb2dc760976449bd0c31e524da4b/tests/conftest.py#L473-L498)
  - [tree comparison function](https://github.com/Connexions/cnx-press/blob/15a074fe27ffeb2dc760976449bd0c31e524da4b/tests/helpers.py#L42-L57)
- In cnx-epub:
  - [html navigation tree parser](https://github.com/Connexions/cnx-press/blob/15a074fe27ffeb2dc760976449bd0c31e524da4b/tests/helpers.py#L42-L57) (maybe not the best example to work from)
  - [various utility functions that work against model based trees](https://github.com/Connexions/cnx-epub/blob/fd3996428e872c2f8069ad1ebd4707a86171e98d/cnxepub/models.py#L124-L204)
- In cnx-db:
   - [shred collxml trigger logic](https://github.com/Connexions/cnx-db/blob/master/cnxdb/archive-sql/schema/shred_collxml.py) (provides an understanding of how the collxml is "shredded" in the database, though it's somewhat difficult to follow)
- (I may have written a parser for collxml somewhere, but I'll need to look through my git stashes)

## Exit Criteria

- The function should output a tree structure that represents the collxml document.
- Fully covered by unit tests.
- The function should not be tied to the database or filesystem. 
- (nice-to-have) The function output data can be compared via the python comparison operatiors (i.e `==` and `!=`).
- (nice-to-have) Be able to able to filter out the differences. (This does not need to be implemented, but if it can be kept in mind, that would be great. I don't know that it's possible, but doing `set` operations of the tree would be ideal for later use.)

**Comment by BryanEliDimas** [comment]
In addition to the information posted in this Issue Description, there are a few things that I would like to note here as well.

From a conversation I had with Ross, my understanding is that the code produced for this issue or task should be enable the following *features* (if not now, in the future):

1. The ability to discern whether or not a Collection has changed, which we can determine by answering the questions: did the order of the modules (or any of the elements) herein change? Or, did the title of any of the modules change? ... which in turn answers the question, does _this_ Publish action require a major version update?
2. The ability to disregard the modules that did not change and only commit/update in the database those which did change.
3. For the modules that changed, the ability to determine whether or not their "local version" (the version that appears in the XML file) matches the latest one in the database.

From a conversation I had with M. Mulich via Slack DMs, my instructions—or his recommendation, rather—was to use Python's [built-in](https://docs.python.org/3.7/library/markup.html) SAX parsing util (`xml.sax`) in order to "build an object-based tree."

As a result, then, I set out to employ some type of meta-programming and custom iterator definition techniques which... turned out to be quite challenging (but at the same time educational) for me as a new Python adopter.

**Comment by BryanEliDimas** [comment]
So far my code answers or enables feature #1. I think, however, that it also establishes the foundation for adding in the functionality to determine #2 (the ability to discern which modules, exactly, changed, and what changed). As for #3, I think that it would have to be baked into a separate, existing module.

**Comment by openstaxalina** [comment]
Assuming new changes are not very time-consuming, this is almost done.

**Comment by BryanEliDimas** [comment]
A title change in the collection itself causes a major rev, but a title change in any of the modules within the collection.xml causes a minor rev.

**Comment by Bkblodget** [comment]
Moved from priority 4 to priority 2 for the Only Publish Content that has Changed epic

**Comment by Bkblodget** [comment]
*Major revision*:
1. Collection structure changes (adding, removing, moving)
2. Collection title changes (this does not include module title changes)

Data that should cause a *Minor rev*:
1. Collection or module metadata changes
- abstract
- subject
2. Parameter changes
3. Collection or module actor/role changes

Data that should not get saved:
1. md:created 
2. md:language
3. md:revised
4. md:license

**Comment by BryanEliDimas** [comment]
@Bkblodget I moved part of the info from this PR to #299. I'll make this a parking lot tomorrow.

**Comment by BryanEliDimas** [comment]
Added a test plan.

**Comment by BryanEliDimas** [comment]
Done updating this issue's description.

**Comment by BryanEliDimas** [comment]
Ready for QA testing.

**Comment by omehes** [comment]
@BryanEliDimas Verified on staging:

First test
1. Using Neb, make a change or a set of changes which should cause a major version rev (criteria listed below) - changed the collection title!
2. Publish the collection.
3. Neb get the latest collection after your changes have been published.
4. Verify that the new version is equal to previous version plus one, and the minor version is equal to one. This information is located in collection.xml -> metadata -> md:version.
OK

Second test
Same steps as above but expect only the minor version to increase by 1 and the major version to remain the same
OK

Third test
Again, using Neb, make a change or a set of changes which are not supposed to cause neither a major version rev nor a minor version rev - No changes made anywhere in the collection or modules!!!
Publish the collection.
NO error message appears -> Expect Neb to give an error message which says that there have been no changes. IS THIS CORRECT?

**Comment by Bkblodget** [comment]
Bug found when trying to publish col11740 US History - lack of subjectlist is causing press to throw an error and prevent publishing

**Comment by omehes** [comment]
Reverified on neb 9.0.1
Looks good
Missing subjectlist does not cause issues anymore.
