### ISSUE TITLE
Bug with Press - preventing publishing

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-press#308]
Steps:
1. run neb publish staging col26294_1.1.1
2. at the prompts, enter a message and correct credentials
Result: publish does not complete and the following message is shown:

ERROR: 
b'{"messages": [{"id": 4, "message": "collection changed", "item": "col26294", "error": "modifying a collection is temporarily disallowed"}]}'
Stop the Press!!! =()

**Comment by BryanEliDimas** [comment]
I removed this issue as a blocker for **Preemptively check credentials** because the bug was not directly related to **Preemptively check credentials**. And the bug has been fixed in Press v8.0.0.

**Comment by BryanEliDimas** [comment]
Moved it to QA testing pipeline. Should be fixed in Press v8.0.0.
cc: @Bkblodget

**Comment by omehes** [comment]
Verified on latest build on staging. I am able to neb publish. Fixed.
